import type { Metadata } from "next";
import {
  Abril_Fatface,
  Gabarito,
  Geist,
  Geist_Mono,
  Libre_Baskerville,
  Outfit,
} from "next/font/google";
import "./globals.css";
import PopUpStateManager from "@/components/popUpManager/popUpStateManger";
import ReduxWrapper from "@/components/reduxWrapper/ReduxWrapper";
import FetchProjectDetails from "@/components/gettingData/FetchProjectDetails";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const outFit = Outfit({
  variable: "--font-outfit-sans",
  subsets: ["latin"],
});

const abrialFatface = Abril_Fatface({
  variable: "--font-abril-fatface",
  weight: "400",
  subsets: ["latin"],
});

const baskerville = Libre_Baskerville({
  variable: "--font-baskerville",
  weight: ["400", "700"],
  subsets: ["latin"],
});

const gabarito = Gabarito({
  variable: "--font-gabarito",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${gabarito.variable} ${baskerville.variable} antialiased dark`}
      >
        <ReduxWrapper>
          <FetchProjectDetails />
          <PopUpStateManager />
        </ReduxWrapper>
        {children}
      </body>
    </html>
  );
}
