import type { Metadata } from "next";
import { Geist, Geist_Mono, Outfit } from "next/font/google";
import "./globals.css";
import PopUpStateManager from "@/components/popUpManager/popUpStateManger";
import ReduxWrapper from "@/components/reduxWrapper/ReduxWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const outFit = Outfit({
  variable: "--font-outfit-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${outFit.variable} ${geistMono.variable} antialiased dark`}
      >
        <ReduxWrapper>
          <PopUpStateManager />
        </ReduxWrapper>
        {children}
      </body>
    </html>
  );
}
